// Static pricing plan configuration â€” NOT mock data
export const PRICING_PLANS = [
  {
    id: "starter",
    name: "Starter",
    price: 49,
    period: "month",
    description: "Perfect for solo agents getting started",
    features: [
      "1 AI Assistant",
      "Up to 50 leads / month",
      "200 conversations / month",
      "WhatsApp integration",
      "Basic analytics",
      "Email support",
    ],
    cta: "Get Started",
    highlighted: false,
  },
  {
    id: "pro",
    name: "Pro",
    price: 99,
    period: "month",
    description: "For growing agencies and teams",
    features: [
      "3 AI Assistants",
      "Up to 500 leads / month",
      "Unlimited conversations",
      "WhatsApp + Web widget",
      "Advanced analytics",
      "Lead qualification AI",
      "Priority support",
      "Custom branding",
    ],
    cta: "Start Free Trial",
    highlighted: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 299,
    period: "month",
    description: "For large agencies and franchises",
    features: [
      "Unlimited AI Assistants",
      "Unlimited leads",
      "Unlimited conversations",
      "All channels",
      "Custom integrations",
      "Dedicated account manager",
      "SLA guarantee",
      "White-label option",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
]
